-- 티켓 테이블 생성
CREATE TABLE VIPTICKET
(
    TICKET_ID NUMBER PRIMARY KEY,
    ID        NUMBER(4),
    TEAM      VARCHAR2(50),
    MATCHDATE VARCHAR2(50),
    LOCATION  VARCHAR2(50)
);

COMMIT;
-- 시퀀스 생성
CREATE SEQUENCE ticket_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

SELECT *
FROM VIPTICKET;

TRUNCATE TABLE VIPTICKET;

